### ISSUE TITLE
[catfish] Vibration doesn't work

### ISSUE THREAD

**Issue by pomputer** [AsteroidOS/meta-smartwatch#90] opened 2022-05-31 19:49 UTC
Unfortunately vibration doesn't work on my watch for some reason. I have a temporary installation.

**Comment by MagneFire** [comment] 2022-06-04 18:17
Thanks for reporting this issue!
I've had a look into this and the cause has been found.

Once https://github.com/AsteroidOS/meta-asteroid/pull/102 is merged and a new nightly is released, this issue should be solved.

**Closed** 2022-06-15 21:22 UTC
Labels: catfish/catfish_ext/catshark
