### ISSUE TITLE
(Dory) cant change watchface and wallpaper

### ISSUE THREAD

**Issue by Adamixdex** [AsteroidOS/meta-smartwatch#147] opened 2023-01-14 21:46 UTC
sorry i cant provide more info because mtp dosent work too and i have no linux (so probably no sdk).

**Comment by MagneFire** [comment] 2023-01-15 18:01
This is a duplicate of https://github.com/AsteroidOS/meta-smartwatch/issues/96

**Closed by MagneFire** 2023-01-15 18:01 UTC
